from kedro.pipeline import Pipeline, node, pipeline

from .nodes import (
    generate_hyde_doc,
    embed_query,
    rank_folders,
    retrieve_chunks_folder_priority,
    rerank_chunks,
    build_prompt,
    generate_answer,
)


def create_pipeline(**kwargs) -> Pipeline:
    return pipeline([
        node(
            func=generate_hyde_doc,
            inputs=[
                "params:question",
                "params:ollama_base_url",
                "params:llm_model",
            ],
            outputs="hyde_document",
            name="generate_hyde_doc_node",
        ),
        node(
            func=embed_query,
            inputs=[
                "hyde_document",
                "params:ollama_base_url",
                "params:embedding_model",
            ],
            outputs="query_embedding",
            name="embed_query_node",
        ),
        node(
            func=rank_folders,
            inputs=[
                "params:question",
                "params:turbovec_persist_path",
                "params:ollama_base_url",
                "params:llm_model",
            ],
            outputs="ranked_folders",
            name="rank_folders_node",
        ),
        node(
            func=retrieve_chunks_folder_priority,
            inputs=[
                "query_embedding",
                "ranked_folders",
                "params:turbovec_persist_path",
                "params:top_k",
                "params:top_folders",
                "params:retrieve_oversample",
                "params:priority_folders",
            ],
            outputs="retrieved_chunks",
            name="retrieve_chunks_node",
        ),
        node(
            func=rerank_chunks,
            inputs=[
                "retrieved_chunks",
                "params:question",
                "params:reranker_model",
                "params:rerank_top_n",
                "params:ollama_base_url",
            ],
            outputs="reranked_chunks",
            name="rerank_chunks_node",
        ),
        node(
            func=build_prompt,
            inputs=[
                "params:question",
                "reranked_chunks",
            ],
            outputs="prompt_data",
            name="build_prompt_node",
        ),
        node(
            func=generate_answer,
            inputs=[
                "prompt_data",
                "params:ollama_base_url",
                "params:llm_model",
            ],
            outputs="query_results",
            name="generate_answer_node",
        ),
    ])
