"""
Prompt templates for ctcobot RAG pipeline and evaluation.
"""

SYSTEM_PROMPT = """You are ctcobot, an HR policy assistant for a tech company.
Your job is to answer employee questions about company policies accurately and concisely.

You will be given a question and a set of relevant excerpts retrieved from the company handbook.
Use ONLY the provided excerpts to answer the question.
Only say "I could not find information about this in the company handbook." when
EVERY excerpt is completely unrelated to the question. If any excerpt contains
partial information, extract and state what is there — do not refuse to answer.

Always be factual, concise, and professional.
Do not make up information or draw on knowledge outside the provided excerpts."""


def format_context(chunks: list[dict]) -> str:
    """
    Format retrieved chunks into a context block for the prompt.

    Args:
        chunks: List of dicts with keys 'text', 'source_path', 'chunk_index'.

    Returns:
        Formatted string with numbered excerpts and source citations.
    """
    lines = []
    for i, chunk in enumerate(chunks, start=1):
        source = chunk.get("source_path", "unknown")
        text = chunk.get("text", "").strip()
        lines.append(f"[Excerpt {i} — source: {source}]\n{text}")
    return "\n\n---\n\n".join(lines)


def format_rag_prompt(question: str, context: str) -> str:
    """
    Assemble the full user-turn prompt with context and question.

    Args:
        question: The employee's question.
        context:  Formatted context string from format_context().

    Returns:
        Full prompt string to send as the user message.
    """
    return (
        f"Use the following excerpts from the company handbook to answer "
        f"the question below.\n\n"
        f"{context}\n\n"
        f"---\n\n"
        f"Question: {question}\n\n"
        f"Answer:"
    )


HYDE_SYSTEM_PROMPT = (
    "You are a company handbook author. Given an employee question about HR or company "
    "policy, write a concise paragraph (3-5 sentences) in the style of a formal policy "
    "document that directly answers the question. "
    "Do not mention the question — write only the policy text. "
    "Output ONLY the paragraph, nothing else."
)


JUDGE_PROMPT = """You are an expert evaluator assessing the quality of an AI assistant's answer to an HR policy question.

You will be given:
- A question asked by an employee
- The expected correct answer
- The AI assistant's actual answer

Score the AI assistant's answer on a scale of 1 to 5 using this rubric:

5 - Excellent: Fully correct, complete, and well-grounded. Matches expected answer closely.
4 - Good: Mostly correct with minor omissions or slight imprecision.
3 - Acceptable: Partially correct. Gets the main point but misses important details.
2 - Poor: Mostly incorrect or incomplete. Contains significant errors or missing key facts.
1 - Unacceptable: Completely wrong, hallucinated, or refused to answer when an answer exists.

Respond with ONLY a JSON object in this exact format, nothing else:
{"score": <integer 1-5>, "reason": "<one sentence explanation>"}"""


def format_judge_prompt(
    question: str,
    expected_answer: str,
    actual_answer: str,
) -> str:
    """
    Format the LLM-as-judge evaluation prompt.

    Args:
        question:        The original employee question.
        expected_answer: The ground truth answer from eval_qa_pairs.csv.
        actual_answer:   The answer generated by ctcobot.

    Returns:
        Full judge prompt string.
    """
    return (
        f"Question: {question}\n\n"
        f"Expected answer: {expected_answer}\n\n"
        f"AI assistant's answer: {actual_answer}\n\n"
        f"Provide your score and reason as JSON."
    )